Z_MIN_BUT_SAFE = -125;
Z_TO_SEED_SAFE = -340;

DEFAULT_Z_TO_WATERING_RADISH = -340;
DEFAULT_INTERVAL_WATERING_RADISH = 24
DEFAULT_AMOUNT_WATERING_RADISH = 700

DEFAULT_Z_TO_WATERING_LETTUCE = -320;
DEFAULT_INTERVAL_WATERING_LETTUCE = 48
DEFAULT_AMOUNT_WATERING_LETTUCE = 200

// readPin: digital mode: 0 ; analog mode: 1
VACUUM_PIN = 9;
WATER_PIN = 8;
LIGHTING_PIN = 7;
HUMIDITY_PIN = 59;
TOOL_CONNECTED_PIN = 63; // DIGITAL mode: 0 means tool connected, 1 means not connected

WATER_CONVERSION_FACTOR = 0.049; // in ml/ms
HUMIDITY_CONVERSION_FACTOR = (WATER_CONVERSION_FACTOR *10000 )/ 336; // in ml/humidity

//humidity interval //
HUMIDITY_INTERVAL = 12;
HUMIDITY_GAP_MEASUREMENT = 20;
HUMIDITY_Z_MEASUREMENT = -522;

// when Tooltip is picked up, how far away the bot needs to start horizontally
TOOLTIP_CATCH_DISTANZ = 100; //mm
SEEDER_POS = { x: 415, y: 15, z: -505 };

WATERIN_TOOL_POS = { x: 2625, y: 145, z: -410 };
SOIL_SENSOR_TOOL_POS = { x: 2625, y: 345, z: -410 };
SEEDER_TOOL_POS = { x: 2625, y: 250, z: -410 };

module.exports = {
  Z_MIN_BUT_SAFE,
  Z_TO_SEED_SAFE,

  DEFAULT_Z_TO_WATERING_RADISH,
  DEFAULT_Z_TO_WATERING_LETTUCE,
  DEFAULT_INTERVAL_WATERING_RADISH,
  DEFAULT_INTERVAL_WATERING_LETTUCE,
  DEFAULT_AMOUNT_WATERING_RADISH,
  DEFAULT_AMOUNT_WATERING_LETTUCE,

  VACUUM_PIN,
  WATER_PIN,
  LIGHTING_PIN,
  HUMIDITY_PIN,
  TOOL_CONNECTED_PIN,
  WATER_CONVERSION_FACTOR,
  TOOLTIP_CATCH_DISTANZ,
  SEEDER_POS,

  WATERIN_TOOL_POS,
  SOIL_SENSOR_TOOL_POS,
  SEEDER_TOOL_POS,

  HUMIDITY_INTERVAL,
  HUMIDITY_GAP_MEASUREMENT,
  HUMIDITY_Z_MEASUREMENT
};
